---
- name: download the Go tarball
  get_url: url="https://storage.googleapis.com/golang/{{ go_tarball }}"
           dest="{{ go_install }}/src/{{ go_tarball }}"

- name: register the current Go version
  become: no
  command: "{{ go_install }}/go/bin/go version"
  ignore_errors: yes
  register: go_version
  changed_when: false

- name: delete the Go directory when Go is not the registered version
  file: path="{{ go_install }}/go"
        state=absent
  ignore_errors: yes
  when: go_version|failed or go_version.stdout != go_version_target

- name: extract the Go tarball when Go is not the registered version
  unarchive: src="{{ go_install }}/src/{{ go_tarball }}"
             dest="{{ go_install }}"
             copy=no
  when: go_version|failed or go_version.stdout != go_version_target

- name: set the GOPATH
  copy: content="export GOPATH={{ go_path }}; export PATH=$PATH:{{ go_install }}/go/bin"
        mode=0755
        dest=/etc/profile.d/gopath.sh

- name: set GOBIN
  copy: content="export GOBIN={{ go_bin }}; export PATH=$PATH:$GOBIN"
        mode=0755
        dest=/etc/profile.d/gobin.sh
